//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Productos
export const AGREGAR_PRODUCTOBD = 'AGREGAR_PRODUCTOBD';
export const OBTENER_PRODUCTOSBD = 'AGREGAR_PRODUCTOBD';

//Carrito
export const AGREGAR_CARRITO = 'AGREGAR_PRODUCTOBD';
export const BORRAR_PRODUCTO_CARRITO = 'BORRAR_PRODUCTO_CARRITO';




